AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an EC2 instance.

Parameters:
  AMIId:
    Type: String
    Description: The ID of the AMI to use for the EC2 instance.
    Default: ami-0b982602dbb32c5bd # Replace with a valid AMI ID for your region
  InstanceType:
    Type: String
    Description: The EC2 instance type.
    Default: t3.micro
  KeyName:
    Type: AWS::EC2::KeyPair::cfn-key
    Description: The name of an existing EC2 KeyPair to enable SSH access to the instance.
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds: !Ref SecurityGroupIds
      Tags:
        - Key: Name
          Value: MyCloudFormationInstance
        - Key: Environment
          Value: Development
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "Hello from CloudFormation!"
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from my EC2 instance!</h1>" > /var/www/html/index.html

Outputs:
  InstanceId:
    Description: The ID of the created EC2 instance.
    Value: !Ref MyEC2Instance
  PublicIp:
    Description: The public IP address of the EC2 instance.
    Value: !GetAtt MyEC2Instance.PublicIp
